# Generated by Django 2.0 on 2018-01-15 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('original', '原创'), ('translation', '翻译'), ('reprint', '转载')], default='original', max_length=20)),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('latest_modify_time', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'IN DRAFTS'), (2, 'PUBLISHED'), (0, 'DELETED')], default=0)),
            ],
            options={
                'verbose_name': '所有文章',
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '文章的类别',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentator', models.CharField(max_length=50)),
                ('comment_content', models.TextField()),
                ('comment_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '文章中的评论',
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=16, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'default_related_name': 'manager',
                'verbose_name': '后台管理员',
                'db_table': 'managers',
            },
        ),
        migrations.CreateModel(
            name='PublishedArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_id', models.IntegerField(unique=True)),
                ('pub_time', models.DateTimeField(auto_now=True)),
                ('url', models.URLField()),
                ('article_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backstage.Article')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backstage.Category')),
            ],
            options={
                'verbose_name': '已发布的文章',
                'db_table': 'published_articles',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='belonged_pub_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.PublishedArticle', to_field='pub_id'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backstage.Comment'),
        ),
    ]
