# Generated by Django 2.0 on 2018-01-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_describe',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(2, 'PUBLISHED'), (1, 'IN DRAFTS'), (0, 'DELETED')], default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('original', '原创'), ('reprint', '转载'), ('translation', '翻译')], default='original', max_length=20),
        ),
    ]
