# Generated by Django 2.0 on 2018-01-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0003_auto_20180120_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(2, 'PUBLISHED'), (1, 'IN DRAFTS'), (0, 'DELETED')], default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('original', '原创'), ('reprint', '转载'), ('translation', '翻译')], default='original', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
