# Generated by Django 2.0 on 2018-01-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0004_auto_20180121_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'IN DRAFTS'), (2, 'PUBLISHED'), (0, 'DELETED')], default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('translation', '翻译'), ('original', '原创'), ('reprint', '转载')], default='original', max_length=20),
        ),
    ]
