# Generated by Django 2.0 on 2018-01-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0005_auto_20180124_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishedarticle',
            old_name='article_id',
            new_name='article',
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'DELETED'), (2, 'PUBLISHED'), (1, 'IN DRAFTS')], default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('reprint', '转载'), ('original', '原创'), ('translation', '翻译')], default='original', max_length=20),
        ),
    ]
