# Generated by Django 2.0 on 2018-01-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0006_auto_20180125_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='html_file_path',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='md_file_path',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'IN DRAFTS'), (2, 'PUBLISHED'), (0, 'DELETED')], default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('reprint', '转载'), ('translation', '翻译'), ('original', '原创')], default='original', max_length=20),
        ),
    ]
