# Generated by Django 2.0 on 2018-01-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0007_auto_20180125_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='html_file_path',
            field=models.URLField(default='/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='md_file_path',
            field=models.URLField(default='/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(2, 'PUBLISHED'), (1, 'IN DRAFTS'), (0, 'DELETED')], default=1),
        ),
    ]
