# Generated by Django 2.0 on 2018-02-01 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0010_auto_20180201_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(2, 'PUBLISHED'), (0, 'DELETED'), (1, 'IN DRAFTS')], default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('original', '原创'), ('reprint', '转载'), ('translation', '翻译')], default='original', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='belonged_pub_article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='comments', related_query_name='comments', to='backstage.PublishedArticle', to_field='pub_id'),
        ),
    ]
