# Generated by Django 2.0 on 2018-02-02 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0013_auto_20180201_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'DELETED'), (1, 'IN DRAFTS'), (2, 'PUBLISHED')], default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('reprint', '转载'), ('original', '原创'), ('translation', '翻译')], default='original', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to='backstage.Comment'),
        ),
    ]
