# Generated by Django 2.0 on 2018-02-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0014_auto_20180202_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='level',
            field=models.CharField(default='common', max_length=9),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(2, 'PUBLISHED'), (0, 'DELETED'), (1, 'IN DRAFTS')], default=1),
        ),
    ]
