# Generated by Django 2.0 on 2018-02-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0015_auto_20180206_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(2, 'PUBLISHED'), (1, 'IN DRAFTS'), (0, 'DELETED')], default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('original', '原创'), ('translation', '翻译'), ('reprint', '转载')], default='original', max_length=20),
        ),
    ]
