# Generated by Django 2.0 on 2018-02-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0016_auto_20180216_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'IN DRAFTS'), (0, 'DELETED'), (2, 'PUBLISHED')], default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('translation', '翻译'), ('reprint', '转载'), ('original', '原创')], default='original', max_length=20),
        ),
        migrations.AlterField(
            model_name='manager',
            name='image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
