# Generated by Django 2.0 on 2018-02-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0017_auto_20180216_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=20)),
                ('concat_info', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'messages',
                'verbose_name': '博客留言',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'IN DRAFTS'), (2, 'PUBLISHED'), (0, 'DELETED')], default=1),
        ),
    ]
