# Generated by Django 2.0 on 2018-02-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0018_auto_20180216_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='compose_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'DELETED'), (2, 'PUBLISHED'), (1, 'IN DRAFTS')], default=1),
        ),
    ]
