# Generated by Django 2.0 on 2018-02-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backstage', '0019_auto_20180216_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='readed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'IN DRAFTS'), (0, 'DELETED'), (2, 'PUBLISHED')], default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('reprint', '转载'), ('original', '原创'), ('translation', '翻译')], default='original', max_length=20),
        ),
    ]
